<?php
    $_productCollection = $this->getProductCollection();
    $_helper = $this->helper('catalog/output');
	$_uniqId = uniqid('grid');
	$options = $this->getDataArray();
	$width1Class = 'width-1';
	$width2Class = 'width-1 width-2';
	$layoutClass = array($width2Class,$width1Class,$width1Class,$width1Class,$width1Class,$width1Class,$width1Class);
	$qsHelper = $this->helper('quickshop');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="icategory-products isotope-wrap codazon-filter codazon-filter-style-02 <?php echo $options['custom_class'] ?>" id="<?php echo $_uniqId ?>">
	<?php $_collectionSize = $_productCollection->count() ?>
    <?php
    	$_columnCount = 4;//$this->getColumnCount();
		$_width = 260; $_height = 320;
	?>
	<div class="products-grid"> 
    <ul class="product-items isotope">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
    		<?php $itemClass = $layoutClass[$i%7]; ?>
            <?php
			switch($itemClass){
				case $width2Class: $_width=480; $_height=480; break;
				default: $_width=230; $_height=230;
			}
			?>
            <li class="item <?php echo $itemClass; ?> product-item">
				<div class="product-item-info">
				<div class="cdz-hover-section">
					<div class="cdz-product-top">
                    <?php if( $this->display('image') ):?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img
                    src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_width,$_height); ?>"
                    alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    <?php endif ?>
                    </div>
                    
                    <div class="cdz-product-wishlist">
                    <?php if( $this->display('wishlist_btn') ):?>
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <div class="actions-secondary show-tooltip">
							<a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="action link-wishlist" data-toggle="tooltip" data-placement="top" title="<?php echo $this->__('Add to Wishlist') ?>" ><?php echo $this->__('Add to Wishlist') ?></a>
							
							
							</div>
                        <?php endif; ?>
					<?php endif ?>
                    </div>
                </div>
				
                    <div class="cdz-product-bottom">
						<div class="cdz-buttons-container">
							<div class="cdz-buttons-inner">
                        	<?php if( $this->display('name') ):?>
                                <h3 class="product-name"><a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>

                    		<?php endif ?>

							<?php if( $this->display('price') ):?>
								<?php echo $this->getPriceHtml($_product, true) ?>
        		            <?php endif ?>
                    
							<?php if( $this->display('rating') ):?>
                                <?php //if($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                <?php //endif; ?>
                            <?php endif; ?>
							
                        	<div class="cdz-buttons">
                        	<?php if( $this->display('addtocart_btn') ):?>
								<?php if($_product->isSaleable()): ?>
                                    <button  data-toggle="tooltip" data-original-title="<?php echo $this->__('Add to Cart') ?>"  type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                            <?php endif ?>
                            <?php echo $qsHelper->getQuickshopHtml($_product) ?>
                            
                            <?php if( $this->display('compare_btn') ):?>
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <a data-toggle="tooltip" data-original-title="<?php echo $this->__('Add to Compare') ?>" href="<?php echo $_compareUrl ?>" class="action link-compare"><?php echo $this->__('Add to Compare') ?></a>
                            <?php endif; ?>
                            <?php endif ?>
                            </div>
                        </div>
					</div>
				</div>
            </li>
            <?php $i++ ?>
        <?php endforeach ?>
		</ul>
		</div>
		<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <script type="text/javascript">
			jQuery('#<?php echo $_uniqId ?> .product-items').switchSliderGrid({
				carousel: {
					responsive:{
						0:{items: 	1},
						320:{items:	1},
						360:{items:	2},
						480:{items:	2},
						600:{items:	3}
					}		
				}
			});
		</script>	
</div>
<?php endif; ?>
