<ul class="cdz-top-link">
    <li class="link wishlist">
        <a href="<?php echo $this->getUrl('wishlist') ?>"><?php echo $this->__('Wishlist') ?></a>
    </li>
    <li class="link compare">
        <a href="javascript:void(0)" onclick="openCompareDialog()"><?php echo $this->__('Compare') ?></a>
    </li>
    <?php  if(Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <li class="link my-account">
        <a href="<?php echo $this->getUrl('customer/account') ?>"><?php echo $this->__('My account') ?></a>
    </li>
    <li class="link logout">
        <a href="<?php echo $this->getUrl('customer/account/logout') ?>"><?php echo $this->__('Logout') ?></a>
    </li>
    <?php else: ?>
    <li class="link signup">
        <a href="<?php echo $this->getUrl('customer/account/create') ?>"><?php echo $this->__('Create an account') ?></a>
    </li>
    <li class="link cdz-top-login cdz-dropdown">
        <a class="cdz-trigger" href="javascript:void(0)"><?php echo $this->__('Sign in') ?></a>
        <div class="cdz-dropdown-content" style="display:none;">
            <?php echo $this->getParentBlock()->getChildHtml('customer_form_mini_login'); ?>                            
        </div>
    </li>                        
    <?php endif ?>
</ul>
<script>
var compareCount = <?php echo Mage::helper('catalog/product_compare')->getItemCount() ?>;
function openCompareDialog(){
	if(compareCount > 0){
		window.open('<?php echo $this->getUrl('catalog/product_compare') ?>','<?php echo $this->__('Compare') ?>','width=800, height=500');
	}else{
		alert('<?php echo $this->__('There is not item in your compare list') ?>')
	}
}
</script>