<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
	$_imgHelper = $this->helper('catalog/image');
	$gallery = 	$this->getGalleryImages();
	$_baseImg = $_imgHelper->init($_product, 'image');
	$minWidth = 450;
	$w = 450 ; //max($minWidth,600);
	$h = round(($w/$_baseImg->getOriginalWidth())*$_baseImg->getOriginalHeight());
?>
<div class="row">
<div class="product-image-moreview col-sm-24" >
    <div class="more-views">
        <div class="fwImage">
            <div id="viewmore-slider" class="royalSlider rsUni product-image-thumbs cdz-zoom">
            	<?php
					$_baseBigImg = (string)$_imgHelper->init($_product, 'image')->resize(null);
					$_baseMainImg = (string)$_imgHelper->init($_product, 'image')->resize($w, $h);
					$_baseSmallImg = (string)$_imgHelper->init($_product, 'image')->resize(88,110);
				?>
	            <div class="rsContent">
                	<a class="rsImg"  href="<?php echo $_baseMainImg ?>"
                    data-rsBigImg="<?php echo $_baseBigImg ?>" />
	                <img data-rsmainimg="<?php echo $_baseMainImg ?>"   class="rsTmb" src="<?php echo $_baseSmallImg ?>" alt="<?php echo $this->getImageLabel() ?>" />
                    </a>
                    <div class="magnify" style="background: url('<?php echo $_baseMainImg; ?>') no-repeat; width:225px; height:225px;"></div>
                </div>
			<?php if( count($gallery) > 0 ): ?>
            <?php $_baseImg = (string)$_imgHelper->init($_product, 'image'); ?>
            <?php foreach ($gallery as $_image): ?>
				<?php
					if( $_baseImg == (string)$_imgHelper->init($_product, 'image', $_image->getFile()) ){
						continue;
					}
					$_img = $_imgHelper->init($_product, 'thumbnail', $_image->getFile());
					$_bigImg = (string)$_img->resize(null);
					$_mainImg = (string)$_img->resize($w, $h);
					$_smallImg = (string)$_img->resize(88,110);
                ?>
                <div class="rsContent">
                    <a class="rsImg"  href="<?php echo $_mainImg ?>"
                        data-rsbigimg="<?php echo $_bigImg ?>" />
                        <img data-rsmainimg="<?php echo $_mainImg ?>" class="rsTmb" src="<?php echo $_smallImg ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
                    </a>
                    <div class="magnify" style="background: url('<?php echo $_mainImg; ?>') no-repeat; width:225px; height:225px;"></div>
                </div>
            <?php endforeach; ?> 
            <?php endif ?>
            </div>
        </div>
    </div>
</div>
</div>
<script>
(function( $ ) {
	var $slider = $('#viewmore-slider');
	$('#cdz-qsiframe .modal-dialog').bind('animated', function() {	
		 $slider.royalSlider({
			fullscreen: {
			  enabled: true,
			  nativeFS: false,
			},
			
			controlNavigation: 'thumbnails',
			thumbs: {
			  orientation: 'vertical',
			  paddingBottom: 0,
			  firstMargin: false,
			  appendSpan: true,
			  autoCenter : false,
			  spacing: 10,
			},  	

			usePreloader: true,
			transitionType:'move',
			imageAlignCenter: true, 
			autoScaleSlider: true, 
			autoScaleSliderWidth: <?php echo $minWidth ?>,
			autoScaleSliderHeight: <?php echo ceil(($minWidth/$w)*$h) - 120 ?>,
			//imageScalePadding: 0,
			autoHeight: false,
			loop: true,
			arrowsNav: true,
			keyboardNavEnabled: true,
			addActiveClass: true
		});

		var $curMainSlide = $slider.find('.rsSlide').first();
		$curMainSlide.addClass('product-image');
		
		var slider =  $slider.data('royalSlider');
		var timeout = false;
		var curId;
		
		$.fn.returnImageSrc = function(){
			$(this).each(function(){
				var $this = $(this);
				$this.click(function(){
					var src = $this.find('.rsNavSelected img').data('rsmainimg');
					$slider.find('.rsActiveSlide .rsMainSlideImage').attr('src',src);
					$slider.find('.rsActiveSlide .magnify').css({background: 'url('+src+') no-repeat'});
				});
			});
		};
		var builSlider = function (){
			$slider.find('.rsSlide').removeClass('product-image');
			$curMainSlide = $slider.find('.rsActiveSlide');	
			var $newImg = $curMainSlide.find('.rsMainSlideImage');
			$curMainSlide.addClass('product-image');
			var $curThumb = $slider.find('.rsNavSelected img.rsTmb');
			if( ($curThumb.data('rsmainimg') != '')){
				$newImg.attr('src',$curThumb.data('rsmainimg'));
			}
		};
		
		slider.ev.on('rsAfterSlideChange', function(event) {
			builSlider();
		});
		slider.ev.on('rsBeforeAnimStart', function(event) {
			
		});
		
		slider.ev.on('rsAfterContentSet', function(e, slideObject) {
			$slider.find('.rsThumbs').returnImageSrc();
		});
		slider.ev.on('rsExitFullscreen', function() {
			$slider.find('.rsContent').cdzZoom();
			$slider.find('.rsThumbs').returnImageSrc();
		});
		slider.ev.on('rsAfterInit', function() {
			$slider.find('.rsContent').cdzZoom();
		});
		slider.ev.on('rsEnterFullscreen', function(){});
		
		$(window).on('swatchUpdateImage',function(event,swatchImageUrl){
			if(!$slider.hasClass('rsFullscreen')){
				var $productImg = $curMainSlide.find('img.rsMainSlideImage');
				$productImg.attr('src',swatchImageUrl);
				$curMainSlide.find('.magnify').css({background:'url('+swatchImageUrl+') no-repeat'});
			}
		});
	});
})( jQuery );
</script>
<script>
if(typeof ConfigurableMediaImages !== 'undefined'){
	ConfigurableMediaImages.updateImage = function(el) {
		var select = $j(el);
		var label = select.find('option:selected').attr('data-label');
		var productId = optionsPrice.productId;
		var selectedLabels = new Array();
		$j('.product-options .super-attribute-select').each(function() {
			var $option = $j(this);
			if($option.val() != '') {
				selectedLabels.push($option.find('option:selected').attr('data-label'));
			}
		});
		var swatchImageUrl = ConfigurableMediaImages.getSwatchImage(productId, label, selectedLabels);
		if(!ConfigurableMediaImages.isValidImage(swatchImageUrl)) {
			return;
		}
		var swatchImage = ConfigurableMediaImages.getImageObject(productId, swatchImageUrl);
		$j(window).trigger('swatchUpdateImage',[swatchImageUrl]);
	};
}
</script>