<?php
    $_product = $this->getProduct();
	$_product->load('media_gallery');
    $_helper = $this->helper('catalog/output');
	$_imgHelper = $this->helper('catalog/image');
	$_gallery = $this->getGalleryImages();
?>
<?php if (count($_gallery) > 0): ?>
<div class="cdz-media-wrap">
<ul class="cdz-media media-slider">
<?php foreach ($_gallery as $_image): ?>
	<?php
		$_smallImg = $_imgHelper->init($_product, 'thumbnail', $_image->getFile())->resize(80,80);
	?>
	<li class="img-item">
    	<img src="<?php echo $_smallImg ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
    </li>
    <li class="img-item">
    	<img src="<?php echo $_smallImg ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
    </li>
    <li class="img-item">
    	<img src="<?php echo $_smallImg ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
    </li>
<?php endforeach ?>
</ul>
</div>
<?php endif ?>

<style>
.cdz-media-wrap {width: 100%; text-align: center; display: block;}
.cdz-media-wrap .cdz-media {display: block;width: 100%;}
.cdz-media-wrap .cdz-media .img-item{float:left;}
.width-1.width-2 .cdz-product-bottom{display: none;}
</style>
<script>
(function($){
	var $media = $('.media-slider');
	$media.addClass('owl-carousel owl-theme');
	$media.owlCarousel({
		dots: false,
		nav: true,
		responsive:{
			0:{items: 	4},
			320:{items:	4},
			480:{items:	4},
			768:{items:	4},
			1024:{items: 4},
			1280:{items: 4}	
		},
		autoRefreshInterval: 1000
	});
})(jQuery)
</script>